In [20]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import os

In [21]:
df = pd.read_csv("./HourlyDataset.csv")
df.shape

(26209, 5)

In [22]:
#Total Null data available in the Dataset
df.isnull().sum()

Time                                             0
Accumulated Precipitation for last 1 h(Avg)    600
Air Temperature 1 Hour Average(Avg)            285
Relative Humidity 1 hour average(Avg)          283
Wind speed (m/s) at 10 m, 1 h avg(Avg)         286
dtype: int64

In [23]:
#changing the string type of time to the date data type
df['Time']=pd.to_datetime(df['Time'])
#changing the format of the date
df['Time']= df["Time"].dt.strftime('%Y-%m-%d %H:%M:%S')
df[:10]

,Time,Accumulated Precipitation for last 1 h(Avg),Air Temperature 1 Hour Average(Avg),Relative Humidity 1 hour average(Avg),"Wind speed (m/s) at 10 m, 1 h avg(Avg)"
0,2019-11-11 06:00:00,0.0,23.400,69.399,2.400
1,2019-11-11 07:00:00,0.0,24.300,64.7,2.500
2,2019-11-11 08:00:00,0.0,25.000,59.3,2.500
3,2019-11-11 09:00:00,0.0,25.400,57.5,2.400
4,2019-11-11 10:00:00,0.0,24.800,60.4,2.300
5,2019-11-11 11:00:00,0.0,23.300,68.4,1.700
6,2019-11-11 12:00:00,0.0,22.099,80.6,1.200
7,2019-11-11 13:00:00,0.0,21.700,80.5,1.099
8,2019-11-11 14:00:00,0.0,21.099,84.899,0.799
9,2019-11-11 15:00:00,0.0,20.000,94.899,0.600

In [24]:
# # data_range = pd.date_range(start="2019-11-11 06:00:00", end="2011-11-07 06:00:00", freq="1H")
# # df.reindex(data_range, fill_value= ' ')
# df.drop('Unnamed: 0', inplace=True, axis=1)
# df.columns

In [25]:
df

,Time,Accumulated Precipitation for last 1 h(Avg),Air Temperature 1 Hour Average(Avg),Relative Humidity 1 hour average(Avg),"Wind speed (m/s) at 10 m, 1 h avg(Avg)"
0,2019-11-11 06:00:00,0.0,23.4,69.399,2.4
1,2019-11-11 07:00:00,0.0,24.3,64.7,2.5
2,2019-11-11 08:00:00,0.0,25.0,59.3,2.5
3,2019-11-11 09:00:00,0.0,25.4,57.5,2.4
4,2019-11-11 10:00:00,0.0,24.8,60.4,2.3
...,...,...,...,...,...
26204,2022-07-11 02:00:00,0.0,15.3,100,1.0
26205,2022-07-11 03:00:00,0.0,17.3,100,0.8
26206,2022-07-11 04:00:00,0.0,19.4,91.6,1.4
26207,2022-07-11 05:00:00,0.0,21.5,74.3,1.9
26208,2022-07-11 06:00:00,0.0,23.3,61.6,2.0

In [26]:
# #Importing the missing hours in the DataFrame
# df['Time'] = pd.to_datetime(df['Time'],format='%Y-%m-%d %H:%M:%S')
# df = df.set_index(['Time']).resample('1H').last().reset_index()
# df

In [27]:
df.isnull().sum()

Time                                             0
Accumulated Precipitation for last 1 h(Avg)    600
Air Temperature 1 Hour Average(Avg)            285
Relative Humidity 1 hour average(Avg)          283
Wind speed (m/s) at 10 m, 1 h avg(Avg)         286
dtype: int64

In [28]:
#downloading the new Dataset:
# df.to_csv("UpdatedDataframe.csv")

In [29]:
missing_data = df.isnull().sum()
missing_data

Time                                             0
Accumulated Precipitation for last 1 h(Avg)    600
Air Temperature 1 Hour Average(Avg)            285
Relative Humidity 1 hour average(Avg)          283
Wind speed (m/s) at 10 m, 1 h avg(Avg)         286
dtype: int64

In [30]:
len(df)
#percentage missing data
Percentage= (missing_data/len(df))*100
Percentage
#by this we got the missing percentage of 4.85%

Time                                           0.000000
Accumulated Precipitation for last 1 h(Avg)    2.289290
Air Temperature 1 Hour Average(Avg)            1.087413
Relative Humidity 1 hour average(Avg)          1.079782
Wind speed (m/s) at 10 m, 1 h avg(Avg)         1.091228
dtype: float64

In [31]:
# df.interpolate(method= 'linear')

,Time,Accumulated Precipitation for last 1 h(Avg),Air Temperature 1 Hour Average(Avg),Relative Humidity 1 hour average(Avg),"Wind speed (m/s) at 10 m, 1 h avg(Avg)"
0,2019-11-11 06:00:00,0.0,23.4,69.399,2.4
1,2019-11-11 07:00:00,0.0,24.3,64.7,2.5
2,2019-11-11 08:00:00,0.0,25.0,59.3,2.5
3,2019-11-11 09:00:00,0.0,25.4,57.5,2.4
4,2019-11-11 10:00:00,0.0,24.8,60.4,2.3
...,...,...,...,...,...
26204,2022-07-11 02:00:00,0.0,15.3,100,1.0
26205,2022-07-11 03:00:00,0.0,17.3,100,0.8
26206,2022-07-11 04:00:00,0.0,19.4,91.6,1.4
26207,2022-07-11 05:00:00,0.0,21.5,74.3,1.9
26208,2022-07-11 06:00:00,0.0,23.3,61.6,2.0

In [32]:
df.isnull().sum()

Time                                             0
Accumulated Precipitation for last 1 h(Avg)    600
Air Temperature 1 Hour Average(Avg)            285
Relative Humidity 1 hour average(Avg)          283
Wind speed (m/s) at 10 m, 1 h avg(Avg)         286
dtype: int64