In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import os

In [2]:
df = pd.read_csv("./HourlyDataset.csv")
df.shape

(26209, 5)

In [3]:
#Total Null data available in the Dataset
df.isnull().sum()

Time                                             0
Accumulated Precipitation for last 1 h(Avg)    600
Air Temperature 1 Hour Average(Avg)            285
Relative Humidity 1 hour average(Avg)          284
Wind speed (m/s) at 10 m, 1 h avg(Avg)         286
dtype: int64

In [4]:
#changing the string type of time to the date data type
df['Time']=pd.to_datetime(df['Time'])
#changing the format of the date
df['Time']= df["Time"].dt.strftime('%Y-%m-%d %H:%M:%S')
df[:10]

,Time,Accumulated Precipitation for last 1 h(Avg),Air Temperature 1 Hour Average(Avg),Relative Humidity 1 hour average(Avg),"Wind speed (m/s) at 10 m, 1 h avg(Avg)"
0,2019-11-11 06:00:00,0.0,23.400,69.399,2.400
1,2019-11-11 07:00:00,0.0,24.300,64.700,2.500
2,2019-11-11 08:00:00,0.0,25.000,59.300,2.500
3,2019-11-11 09:00:00,0.0,25.400,57.500,2.400
4,2019-11-11 10:00:00,0.0,24.800,60.400,2.300
5,2019-11-11 11:00:00,0.0,23.300,68.400,1.700
6,2019-11-11 12:00:00,0.0,22.099,80.600,1.200
7,2019-11-11 13:00:00,0.0,21.700,80.500,1.099
8,2019-11-11 14:00:00,0.0,21.099,84.899,0.799
9,2019-11-11 15:00:00,0.0,20.000,94.899,0.600

In [5]:
# # data_range = pd.date_range(start="2019-11-11 06:00:00", end="2011-11-07 06:00:00", freq="1H")
# # df.reindex(data_range, fill_value= ' ')
# df.drop('Unnamed: 0', inplace=True, axis=1)
# df.columns

In [6]:
df

,Time,Accumulated Precipitation for last 1 h(Avg),Air Temperature 1 Hour Average(Avg),Relative Humidity 1 hour average(Avg),"Wind speed (m/s) at 10 m, 1 h avg(Avg)"
0,2019-11-11 06:00:00,0.0,23.4,69.399,2.4
1,2019-11-11 07:00:00,0.0,24.3,64.700,2.5
2,2019-11-11 08:00:00,0.0,25.0,59.300,2.5
3,2019-11-11 09:00:00,0.0,25.4,57.500,2.4
4,2019-11-11 10:00:00,0.0,24.8,60.400,2.3
...,...,...,...,...,...
26204,2022-07-11 02:00:00,0.0,15.3,100.000,1.0
26205,2022-07-11 03:00:00,0.0,17.3,100.000,0.8
26206,2022-07-11 04:00:00,0.0,19.4,91.600,1.4
26207,2022-07-11 05:00:00,0.0,21.5,74.300,1.9
26208,2022-07-11 06:00:00,0.0,23.3,61.600,2.0

In [7]:
# #Importing the missing hours in the DataFrame
# df['Time'] = pd.to_datetime(df['Time'],format='%Y-%m-%d %H:%M:%S')
# df = df.set_index(['Time']).resample('1H').last().reset_index()
# df

In [8]:
df.isnull().sum()

Time                                             0
Accumulated Precipitation for last 1 h(Avg)    600
Air Temperature 1 Hour Average(Avg)            285
Relative Humidity 1 hour average(Avg)          284
Wind speed (m/s) at 10 m, 1 h avg(Avg)         286
dtype: int64

In [9]:
#downloading the new Dataset:
# df.to_csv("UpdatedDataframe.csv")

In [10]:
missing_data = df.isnull().sum()
missing_data

Time                                             0
Accumulated Precipitation for last 1 h(Avg)    600
Air Temperature 1 Hour Average(Avg)            285
Relative Humidity 1 hour average(Avg)          284
Wind speed (m/s) at 10 m, 1 h avg(Avg)         286
dtype: int64

In [11]:
len(df)
#percentage missing data
Percentage= (missing_data/len(df))*100
Percentage
#by this we got the missing percentage of 4.85%

Time                                           0.000000
Accumulated Precipitation for last 1 h(Avg)    2.289290
Air Temperature 1 Hour Average(Avg)            1.087413
Relative Humidity 1 hour average(Avg)          1.083597
Wind speed (m/s) at 10 m, 1 h avg(Avg)         1.091228
dtype: float64

In [12]:
#set date as index:
df.set_index('Time', inplace=True)

In [13]:
df[1386:1396]

,Accumulated Precipitation for last 1 h(Avg),Air Temperature 1 Hour Average(Avg),Relative Humidity 1 hour average(Avg),"Wind speed (m/s) at 10 m, 1 h avg(Avg)"
Time,,,,
2020-08-01 00:00:00,NaN,NaN,NaN,NaN
2020-08-01 01:00:00,NaN,9.2,100.0,0.7
2020-08-01 02:00:00,0.0,8.7,100.0,0.9
2020-08-01 03:00:00,NaN,9.3,100.0,1.1
2020-08-01 04:00:00,NaN,10.0,100.0,1.0
2020-08-01 05:00:00,0.0,10.4,100.0,1.0
2020-08-01 06:00:00,NaN,12.1,100.0,0.9
2020-08-01 07:00:00,NaN,NaN,NaN,NaN
2020-08-01 08:00:00,0.0,13.6,99.2,1.6
2020-08-01 09:00:00,NaN,NaN,NaN,NaN

In [14]:
#applying interpolation into the dataframe
df1=df.interpolate(method='linear')

In [15]:
#Checking the dataframe whether it is applied or not
df1[1386:1396]

,Accumulated Precipitation for last 1 h(Avg),Air Temperature 1 Hour Average(Avg),Relative Humidity 1 hour average(Avg),"Wind speed (m/s) at 10 m, 1 h avg(Avg)"
Time,,,,
2020-08-01 00:00:00,0.000000,9.233333,100.00,0.733333
2020-08-01 01:00:00,0.000000,9.200000,100.00,0.700000
2020-08-01 02:00:00,0.000000,8.700000,100.00,0.900000
2020-08-01 03:00:00,0.000000,9.300000,100.00,1.100000
2020-08-01 04:00:00,0.000000,10.000000,100.00,1.000000
2020-08-01 05:00:00,0.000000,10.400000,100.00,1.000000
2020-08-01 06:00:00,0.000000,12.100000,100.00,0.900000
2020-08-01 07:00:00,0.000000,12.850000,99.60,1.250000
2020-08-01 08:00:00,0.000000,13.600000,99.20,1.600000
2020-08-01 09:00:00,0.066667,13.050000,98.25,1.400000

In [16]:
df1.isnull().sum()

Accumulated Precipitation for last 1 h(Avg)    0
Air Temperature 1 Hour Average(Avg)            0
Relative Humidity 1 hour average(Avg)          0
Wind speed (m/s) at 10 m, 1 h avg(Avg)         0
dtype: int64

In [17]:
# df1.to_csv('CleanedHourlyData.csv')

In [19]:
df1.describe()

,Accumulated Precipitation for last 1 h(Avg),Air Temperature 1 Hour Average(Avg),Relative Humidity 1 hour average(Avg),"Wind speed (m/s) at 10 m, 1 h avg(Avg)"
count,26209.000000,26209.000000,26209.000000,26209.000000
mean,0.556503,20.270232,83.905331,1.491812
std,3.148025,6.309492,19.310152,0.714243
min,0.000000,3.500000,13.200000,0.000000
25%,0.000000,15.600000,70.600000,1.000000
50%,0.000000,21.600000,93.000000,1.400000
75%,0.000000,24.500000,100.000000,1.900000
max,76.000000,37.200000,100.000000,10.200000